workspace:
  base: /go
  path: src/github.com/uswitch/klint

pipeline:
  build:
    when:
      event: push
    image: golang:1.18
    environment:
      - GO111MODULE=on
    commands:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/klint .

  publish:
    when:
      event: push
    image: plugins/docker
    repo: registry.usw.co/cloud/klint
    tags: [ "${DRONE_COMMIT_SHA}", "latest" ]
